import sharp from "sharp";
import { test, expect } from "@playwright/test";
async function enter(page: import("@playwright/test").Page) { await page.goto("/demonstracao-imobiliaria/equipe/cadastro/"); await page.getByRole("button", { name: "Conhecer a área da equipe" }).click(); await expect(page.locator(".editor-form")).toBeVisible(); }
test("dedicated editor restores tags, masks, address and own photos after reload, with responsive layouts", async ({ page }) => {
  await page.route("https://viacep.com.br/**", (route) => route.fulfill({ json: { localidade: "Taubaté", uf: "SP", bairro: "Centro", logradouro: "Rua de exemplo" } }));
  await page.route("**/api/imobiliaria/cadastro", (route) => route.fulfill({ json: { tags: ["Piscina", "Escritório"] } }));
  await enter(page); await expect(page.getByLabel("Dormitórios", { exact: true })).toHaveValue("1"); await expect(page.getByLabel("Banheiros", { exact: true })).toHaveValue("1"); await expect(page.locator(".editor-photos img")).toHaveCount(0); await expect(page.getByText("Começar com uma galeria")).toHaveCount(0);
  await page.getByLabel("CEP", { exact: true }).fill("12010000"); await expect(page.getByLabel("Cidade", { exact: true })).toHaveValue("Taubaté"); await expect(page.getByLabel("Rua", { exact: true })).toHaveValue("Rua de exemplo");
  await page.getByLabel("Finalidade", { exact: true }).selectOption("ambos"); await page.getByLabel("Preço de venda", { exact: true }).fill("1250000,50"); await page.getByLabel("Aluguel mensal", { exact: true }).fill("4500"); await page.getByLabel("Área construída", { exact: true }).fill("180,5");
  await expect(page.getByLabel("Preço de venda", { exact: true })).toHaveValue("1.250.000,50"); await expect(page.locator(".masked-field")).toContainText(["R$", "R$", "m²"]);
  await page.getByLabel("Diferenciais", { exact: true }).fill("piscna"); await page.getByLabel("Diferenciais", { exact: true }).press("Enter"); await expect(page.locator(".feature-tags")).toContainText("Piscina");
  await page.getByLabel("Diferenciais", { exact: true }).fill("PISCINA, escritorio,"); await expect(page.locator(".feature-tags>span")).toHaveCount(2);
  await page.getByLabel("Cor / tom", { exact: true }).selectOption("other"); await page.getByLabel("Outra cor", { exact: true }).fill("terracota");
  await page.locator('input[type="file"]').setInputFiles({ name: "propria.png", mimeType: "image/png", buffer: await sharp({ create: { width: 32, height: 24, channels: 3, background: "#b79c70" } }).png().toBuffer() }); await expect(page.locator(".editor-photos img")).toHaveCount(1);
  await expect(page.getByText("Rascunho salvo neste navegador", { exact: true })).toBeVisible(); await page.reload(); await expect(page.locator(".editor-photos img")).toHaveCount(1); await expect(page.getByLabel("Preço de venda", { exact: true })).toHaveValue("1.250.000,50"); await expect(page.locator(".feature-tags>span")).toHaveCount(2); await expect(page.getByLabel("Outra cor", { exact: true })).toHaveValue("terracota");
  for (const width of [320, 390, 768, 1440]) { await page.setViewportSize({ width, height: 900 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); }
  await page.getByLabel("Tipo", { exact: true }).selectOption("Terreno"); await expect(page.getByLabel("Dormitórios", { exact: true })).toHaveCount(0); await expect(page.getByLabel("Área do terreno", { exact: true })).toBeVisible();
});
test("AI asks missing fields and confirmation, persists suggestion, fills reviewed text without sending address or photos", async ({ page }) => {
  let body: Record<string, unknown> | undefined;
  await page.route("https://viacep.com.br/**", (route) => route.fulfill({ json: { localidade: "Taubaté", uf: "SP", bairro: "Centro", logradouro: "Rua de exemplo" } }));
  await page.route("**/api/imobiliaria/cadastro", (route) => { body = route.request().postDataJSON(); return route.fulfill({ json: { title: "Casa em Taubaté", description: "Casa com 180 m², um dormitório e um banheiro." } }); });
  await enter(page); await page.getByRole("button", { name: "Ajuda com IA", exact: true }).click(); const modal = page.getByRole("dialog", { name: "Ajuda com IA" }); await expect(modal).toContainText("ainda preciso"); await expect(modal.getByRole("button", { name: "Gerar sugestão" })).toBeDisabled();
  await modal.getByLabel("Finalidade", { exact: true }).selectOption("venda"); await modal.getByLabel("CEP", { exact: true }).fill("12010000"); await expect(modal.getByLabel("Cidade", { exact: true })).toHaveValue("Taubaté"); await modal.getByLabel("Número / S/N", { exact: true }).fill("999"); await modal.getByLabel("Preço de venda", { exact: true }).fill("900000"); await modal.getByLabel("Área construída", { exact: true }).fill("180"); await modal.getByRole("checkbox").check(); await modal.getByRole("button", { name: "Gerar sugestão" }).click(); await expect(modal.locator(".editor-proposal")).toContainText("Casa em Taubaté");
  expect(JSON.stringify(body)).not.toMatch(/cep|addressNumber|photos|999/); await page.reload(); const restored = page.getByRole("dialog", { name: "Ajuda com IA" }); await expect(restored.locator(".editor-proposal")).toContainText("Casa em Taubaté"); await expect(restored.getByRole("checkbox")).not.toBeChecked(); await restored.getByRole("button", { name: "Usar este texto" }).click(); await expect(page.getByLabel("Título", { exact: true })).toHaveValue("Casa em Taubaté"); await expect(page.getByLabel("Descrição", { exact: true })).toHaveValue(/180 m²/);
});
test("land offered for sale and rent publishes with separate prices and remains searchable by custom color and type", async ({ page }) => {
  await enter(page);
  await page.getByLabel("Tipo", { exact: true }).selectOption("Terreno"); await page.getByLabel("Finalidade", { exact: true }).selectOption("ambos");
  await page.getByLabel("Cidade", { exact: true }).fill("Taubaté"); await page.getByLabel("Bairro", { exact: true }).fill("Centro"); await page.getByLabel("Preço de venda", { exact: true }).fill("800000"); await page.getByLabel("Aluguel mensal", { exact: true }).fill("3000"); await page.getByLabel("Área do terreno", { exact: true }).fill("400"); await page.getByLabel("Título", { exact: true }).fill("Terreno para novos projetos"); await page.getByLabel("Descrição", { exact: true }).fill("Terreno de 400 m² no Centro."); await page.getByLabel("Cor / tom", { exact: true }).selectOption("other"); await page.getByLabel("Outra cor", { exact: true }).fill("Terracota");
  await page.getByRole("checkbox", { name: "Conferi os dados, valores e fotografias" }).check(); await page.getByRole("button", { name: "Publicar imóvel" }).click(); await expect(page.locator(".editor-form .ai-error")).toContainText("Adicione pelo menos uma foto");
  await page.locator('input[type="file"]').setInputFiles({ name: "terreno.png", mimeType: "image/png", buffer: await sharp({ create: { width: 32, height: 24, channels: 3, background: "#ac8159" } }).png().toBuffer() }); await expect(page.locator(".editor-photos img")).toHaveCount(1); await page.getByRole("checkbox", { name: "Conferi os dados, valores e fotografias" }).check(); await page.getByRole("button", { name: "Publicar imóvel" }).click(); await expect(page.locator(".editor-success")).toBeVisible(); await page.getByRole("link", { name: "Ver anúncio" }).click(); await expect(page.locator(".detail-price")).toContainText("800.000"); await expect(page.locator(".cost-list")).toContainText("3.000"); await expect(page.locator("#financiamento")).toBeVisible();
  await page.goto("/demonstracao-imobiliaria/?purpose=locacao&type=Terreno&color=terracota&maxPrice=3500#imoveis"); await expect(page.locator(".property-card")).toHaveCount(1); await expect(page.locator(".card-bottom")).toContainText("3.000"); await page.reload(); await expect(page.locator(".property-card")).toHaveCount(1);
  await page.goto("/demonstracao-imobiliaria/?purpose=venda&type=Terreno&maxPrice=3500#imoveis"); await expect(page.locator(".property-card")).toHaveCount(0);
});
