import { ArrowDown, ArrowRight, ArrowUpRight, Camera, MapPin, Phone, Sparkles } from "lucide-react";
import { MotionProvider } from "@/components/taeko/motion-provider";
import { FrameSequenceBackground } from "@/components/taeko/frame-sequence-background";
import { heroMedia } from "@/lib/hero-media";
import { contact } from "@/lib/taeko";
function Wordmark() { return <span className="wordmark">taeko<span>NOIVAS</span></span>; }
export default function Home() {
  return <>
    <a className="skip-link" href="#conteudo">Pular para o conteúdo</a>
    <header className="site-header"><a href="#inicio" aria-label="Taeko Noivas, início"><Wordmark /></a><nav aria-label="Navegação principal"><a href="#vestidos">Os vestidos</a><a href="#taeko">A Taeko</a><a href="#contato">Encontre-nos</a></nav><a className="header-contact" href={contact.whatsapp} target="_blank" rel="noreferrer">Vamos conversar <ArrowUpRight size={16}/></a></header>
    <MotionProvider><main id="conteudo">
      <section className="hero" id="inicio" aria-labelledby="hero-title"><FrameSequenceBackground config={heroMedia}/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow hero-reveal"><span className="small-line"/> TAEKO NOIVAS · JACAREÍ</p><h1 id="hero-title"><span className="hero-reveal">O seu sonho,</span><span className="hero-reveal">feito <em>sob</em></span><span className="hero-reveal"><em>medida.</em></span></h1><p className="hero-description hero-reveal">Há 40 anos transformando sonhos<br/>em realidade. O próximo pode ser o seu.</p><a className="button hero-reveal" href={contact.whatsapp} target="_blank" rel="noreferrer">Converse com a Taeko <ArrowUpRight size={18}/></a></div><div className="hero-bottom"><a href="#vestidos"><ArrowDown size={15}/> UM NOVO CAPÍTULO COMEÇA AQUI</a><span>CONFECÇÃO SOB MEDIDA</span></div></section>
      <div className="signature-strip"><span>Uma história de amor.</span><Sparkles size={17} strokeWidth={1}/><span>Um vestido só seu.</span><Sparkles size={17} strokeWidth={1}/><span>Um momento para sempre.</span></div>
      <section className="collection section-pad" id="vestidos" aria-labelledby="collection-title"><div className="section-heading" data-reveal><div><p className="eyebrow">PARA O SEU GRANDE DIA</p><h2 id="collection-title">Tão único quanto<br/><em>a sua história.</em></h2></div><div className="heading-aside"><p>O primeiro olhar. A delicadeza dos detalhes.<br/>A inspiração para o vestido dos seus sonhos.</p><a className="text-link" href={contact.instagram} target="_blank" rel="noreferrer">Conheça as noivas Taeko <ArrowUpRight size={17}/></a></div></div><div className="editorial-grid">
        <a className="editorial-card" href={contact.instagram} target="_blank" rel="noreferrer" data-reveal><div className="editorial-photo portrait-photo"><img src="/demonstracao-taeko/media/editorial-portrait.webp" alt="Inspiração ilustrativa: vestido de noiva com detalhes delicados" width="1024" height="1536" loading="lazy"/></div><div className="editorial-caption"><div><span className="eyebrow">01 / INSPIRAÇÃO</span><h3>A beleza dos detalhes</h3></div><ArrowUpRight size={24} strokeWidth={1}/></div></a>
        <a className="editorial-card editorial-card-offset" href={contact.instagram} target="_blank" rel="noreferrer" data-reveal><div className="editorial-photo landscape-crop"><img src="/demonstracao-taeko/media/hero-editorial.webp" alt="Inspiração ilustrativa: noiva com vestido de renda em tons claros" width="1536" height="1024" loading="lazy"/></div><div className="editorial-caption"><div><span className="eyebrow">02 / INSPIRAÇÃO</span><h3>O encanto de ser você</h3></div><ArrowUpRight size={24} strokeWidth={1}/></div></a>
      </div><p className="image-note">Imagens editoriais ilustrativas. Veja os vestidos e as noivas reais da Taeko no Instagram.</p></section>
      <section className="about" id="taeko" aria-labelledby="about-title"><div className="about-visual"><img src="/demonstracao-taeko/media/editorial-portrait.webp" alt="Detalhes de um vestido em fotografia editorial ilustrativa" width="1024" height="1536" loading="lazy"/><span className="image-label">O CUIDADO MORA NOS DETALHES</span></div><div className="about-copy" data-reveal><p className="eyebrow">A ESSÊNCIA TAEKO</p><h2 id="about-title">Sonhos passam.<br/><em>Histórias ficam.</em></h2><div className="anniversary"><span>40</span><div>ANOS<br/>TRANSFORMANDO SONHOS<br/>EM REALIDADE</div></div><p>Há momentos que merecem um vestido especial. Em Jacareí, a Taeko Noivas une sua história à confecção sob medida para fazer parte do seu grande dia.</p><p>Conte como você imagina esse momento.<br/>Vamos começar essa conversa?</p><a className="text-link" href={contact.whatsapp} target="_blank" rel="noreferrer">Quero falar sobre meu vestido <ArrowRight size={18}/></a></div></section>
      <section className="invitation section-pad" id="contato" aria-labelledby="contact-title"><p className="eyebrow" data-reveal>DO PRIMEIRO SONHO AO GRANDE SIM</p><h2 id="contact-title" data-reveal>Vamos escrever<br/><em>o seu próximo capítulo?</em></h2><a className="button" href={contact.whatsapp} target="_blank" rel="noreferrer" data-reveal>Converse pelo WhatsApp <ArrowUpRight size={18}/></a><div className="contact-grid"><div><MapPin size={20} strokeWidth={1}/><p className="eyebrow">VENHA NOS CONHECER</p><p>Av. Adhemar Pereira de Barros, 1737<br/>Jacareí · SP · 12328-300</p><a className="text-link" href={contact.map} target="_blank" rel="noreferrer">Como chegar <ArrowUpRight size={14}/></a></div><div><Phone size={20} strokeWidth={1}/><p className="eyebrow">UMA CONVERSA ESPECIAL</p><a href="tel:+5512997550893">(12) 99755-0893</a><p>Consulte os horários pelo WhatsApp.</p></div><div><Camera size={20} strokeWidth={1}/><p className="eyebrow">MAIS HISTÓRIAS, MAIS INSPIRAÇÃO</p><a href={contact.instagram} target="_blank" rel="noreferrer">@taekonoivas <ArrowUpRight size={14}/></a><p>Acompanhe a Taeko no Instagram.</p></div></div></section>
    </main><footer><a href="#inicio" aria-label="Voltar ao início"><Wordmark/></a><span>FEITO PARA CELEBRAR A SUA HISTÓRIA.</span><span>Taeko Noivas · Jacareí</span></footer></MotionProvider>
  </>;
}
