"use client";
import { restoreTeam, seedTeam, teamKey } from "@/lib/team";
import { apiUrl } from "@/lib/api-url";
import { useEffect, useState, useRef, type FormEvent } from "react";
import Link from "next/link";
import Image from "next/image";
import { ArrowLeft, ArrowUpRight, Sparkles, X, Check, ImagePlus } from "lucide-react";
import { useLocalCatalog } from "./local-catalog";
import { Modal } from "./modal";
import { asset, money } from "@/lib/format";
import { propertyHref } from "@/lib/local-properties";
import { capitalize, colors, draftPrefix, featureTags, initialDraft, restoreDraft, type EditorDraft } from "@/lib/editor";
import { readDraft, writeDraft } from "@/lib/draft-store";
import { commercialTypes, landTypes, propertyTypes, type Property, type PropertyImage } from "@/lib/property";
import { validateCopy, validateCopyFacts } from "@/lib/editor-ai";

export function PropertyEditor({ property }: { property?: Property }) {
  const { save, properties } = useLocalCatalog();
  const [developments, setDevelopments] = useState<string[]>([]);
  useEffect(() => { queueMicrotask(() => { const fallback = seedTeam(properties); try { setDevelopments(restoreTeam(JSON.parse(localStorage.getItem(teamKey) || "null"), fallback).developments.map((item) => item.name)); } catch { setDevelopments(fallback.developments.map((item) => item.name)); } }); }, [properties]);
  const key = draftPrefix + (property?.reference ?? "new");
  const [draft, setDraft] = useState<EditorDraft>(() => initialDraft(property));
  const [ready, setReady] = useState(false), [cache, setCache] = useState("Preparando rascunho…"), [error, setError] = useState(""), [busy, setBusy] = useState(false), [cepStatus, setCepStatus] = useState(""), [aiBusy, setAiBusy] = useState(false), [aiError, setAiError] = useState(""), [tagStatus, setTagStatus] = useState(""), [published, setPublished] = useState<Property | null>(null), [publishConfirmed, setPublishConfirmed] = useState(false), [discard, setDiscard] = useState(false);
  const draftRef = useRef(draft);
  useEffect(() => { draftRef.current = draft; }, [draft]);
  const finished = useRef(false), aiController = useRef<AbortController | null>(null);
  const v = draft.values, isLand = landTypes.includes(v.type), noRooms = isLand || commercialTypes.includes(v.type);
  useEffect(() => { let active = true; queueMicrotask(() => { if (active) setPublishConfirmed(false); }); return () => { active = false; }; }, [draft.values, draft.photos, draft.tags]);
  function patch(values: Record<string, string>) { setPublishConfirmed(false); setDraft((current) => ({ ...current, values: { ...current.values, ...values }, aiConfirmed: false, aiProposal: null })); }
  useEffect(() => { let active = true; readDraft(key).then((value) => { if (active) { setDraft(restoreDraft(value, initialDraft(property))); setReady(true); setCache(value ? "Rascunho recuperado" : "Rascunho salvo neste navegador"); } }).catch(() => { if (active) { setReady(true); setCache("Não foi possível recuperar o rascunho. Verifique o armazenamento do navegador."); } }); return () => { active = false; }; }, [key, property]);
  useEffect(() => { if (!ready || finished.current) return; let active = true; queueMicrotask(() => { if (active) setCache("Salvando rascunho…"); }); writeDraft(key, { ...draft, savedAt: new Date().toISOString() }).then(() => { if (active) setCache("Rascunho salvo neste navegador"); }).catch((reason) => { if (active) setCache((reason as Error).message); }); return () => { active = false; }; }, [draft, ready, key]);
  useEffect(() => () => aiController.current?.abort(), []);
  useEffect(() => {
    const cep = v.cep.replace(/\D/g, ""); if (cep.length !== 8) return;
    const controller = new AbortController(); const snapshot = { ...draftRef.current.values };
    const timer = setTimeout(async () => { setCepStatus("Consultando CEP…"); try { const response = await fetch(`https://viacep.com.br/ws/${cep}/json/`, { signal: AbortSignal.any([controller.signal, AbortSignal.timeout(8000)]), referrerPolicy: "no-referrer" }); if (!response.ok) throw new Error(); const data = await response.json(); if (data.erro || typeof data.localidade !== "string" || typeof data.uf !== "string") throw new Error(); if (controller.signal.aborted) return; setDraft((current) => { const values = { ...current.values }; const found: Record<string, string> = { city: data.localidade, state: data.uf, neighborhood: typeof data.bairro === "string" ? data.bairro : "", street: typeof data.logradouro === "string" ? data.logradouro : "" }; for (const [field, value] of Object.entries(found)) if (values[field] === snapshot[field] && value) values[field] = value.slice(0, 120); return { ...current, values, aiConfirmed: false }; }); setCepStatus("Endereço preenchido. Confira número e demais dados."); } catch { if (!controller.signal.aborted) setCepStatus("CEP não encontrado ou consulta indisponível. Preencha o endereço manualmente."); } }, 350);
    return () => { clearTimeout(timer); controller.abort(); };
  }, [v.cep]);
  const tagsJson = JSON.stringify(draft.tags);
  useEffect(() => {
    if (!ready || draft.tags.length === 0) return;
    const controller = new AbortController(); const timer = setTimeout(async () => { setTagStatus("Conferindo escrita…"); try { const response = await fetch(apiUrl("/api/imobiliaria/cadastro"), { method: "POST", signal: AbortSignal.any([controller.signal, AbortSignal.timeout(30000)]), headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode: "tags", tags: JSON.parse(tagsJson) }) }); const data = await response.json(); if (!response.ok || !Array.isArray(data.tags) || !data.tags.every((tag: unknown) => typeof tag === "string")) throw new Error(); const tags = featureTags(data.tags); if (controller.signal.aborted) return; if (JSON.stringify(tags) !== tagsJson) setDraft((current) => ({ ...current, tags })); setTagStatus("Escrita conferida"); } catch { if (!controller.signal.aborted) setTagStatus("Padronização local aplicada. Revisão com IA indisponível no momento."); } }, 700); return () => { clearTimeout(timer); controller.abort(); };
  // The serialized list is the dependency: editing another field must not resend tags.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tagsJson, ready]);
  function commitTags(value = draft.tagInput) { setDraft((current) => ({ ...current, tags: featureTags([...current.tags, ...value.split(/[,\n]/)]), tagInput: "", aiConfirmed: false, aiProposal: null })); }
  async function upload(files: FileList | null) {
    if (!files?.length) return; setBusy(true); setError("");
    try { if (files.length + draft.photos.length > 6) throw new Error("Escolha até seis fotos no total."); const photos: PropertyImage[] = [];
      for (const file of Array.from(files)) { if (!["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > 5 * 1024 * 1024) throw new Error("Use JPG, PNG ou WebP de até 5 MB por foto."); let bitmap: ImageBitmap; try { bitmap = await createImageBitmap(file); } catch { throw new Error("Não consegui abrir esta foto. Escolha outra imagem."); }
        try { const scale = Math.min(1, 1024 / Math.max(bitmap.width, bitmap.height)); const canvas = document.createElement("canvas"); canvas.width = Math.max(1, Math.round(bitmap.width * scale)); canvas.height = Math.max(1, Math.round(bitmap.height * scale)); canvas.getContext("2d")!.drawImage(bitmap, 0, 0, canvas.width, canvas.height); const path = canvas.toDataURL("image/webp", .72); if (path.length > 700000) throw new Error("Esta foto ainda ficou grande. Escolha uma imagem menor."); photos.push({ path, thumbnail: path, width: canvas.width, height: canvas.height, sourceUrl: "", sha256: "", author: "Foto cadastrada pela equipe" }); } finally { bitmap.close(); } }
      setDraft((current) => ({ ...current, photos: [...current.photos, ...photos] }));
    } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); }
  }
  function facts() { return validateCopyFacts({ type: v.type, purpose: v.purpose, city: v.city, neighborhood: v.neighborhood, development: v.development, price: Number(v.price), rentPrice: v.purpose === "ambos" ? Number(v.rentPrice) : null, area: Number(isLand ? v.landArea : v.builtArea), bedrooms: noRooms ? 0 : Number(v.bedrooms), bathrooms: noRooms ? 0 : Number(v.bathrooms), features: featureTags([...draft.tags, ...draft.tagInput.split(",")]) }); }
  const missing = [!v.purpose && "finalidade (venda ou locação)",!/^\d{8}$/.test(v.cep.replace(/\D/g, "")) && "CEP", !v.addressNumber.trim() && "número (ou S/N)", !v.city.trim() && "cidade", !v.neighborhood.trim() && "bairro", !(Number(v.price) > 0) && (v.purpose === "locacao" ? "aluguel mensal" : "valor de venda"), v.purpose === "ambos" && !(Number(v.rentPrice) > 0) && "aluguel mensal", !(Number(isLand ? v.landArea : v.builtArea) > 0) && "área"].filter(Boolean);
  async function generate() { setAiError(""); if (missing.length || !draft.aiConfirmed) { setAiError("Complete os campos e confirme os dados para gerar o texto."); return; } setAiBusy(true); const controller = new AbortController(); aiController.current = controller; try { const response = await fetch(apiUrl("/api/imobiliaria/cadastro"), { method: "POST", signal: AbortSignal.any([controller.signal, AbortSignal.timeout(30000)]), headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode: "copy", facts: facts() }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "IA indisponível."); const proposal = validateCopy(data); setDraft((current) => ({ ...current, aiProposal: proposal })); } catch (reason) { if (!controller.signal.aborted) setAiError((reason as Error).message); } finally { setAiBusy(false); } }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (busy) return; setError("");
    if (!publishConfirmed) { setError("Confirme que conferiu o anúncio antes de publicar."); return; }
    if (!v.purpose) { setError("Escolha se o imóvel é para venda, locação ou ambos."); return; }
    if (!event.currentTarget.checkValidity()) { setError("Confira os campos obrigatórios destacados antes de publicar."); event.currentTarget.reportValidity(); return; }
    if (!draft.photos.length) { setError("Adicione pelo menos uma foto do imóvel."); return; }
    if (v.cep && v.cep.replace(/\D/g, "").length !== 8) { setError("Revise o CEP."); return; }
    const numeric = (key: string) => v[key] ? Number(v[key]) : null;
    const tags = featureTags([...draft.tags, ...draft.tagInput.split(",")]);
    const item: Property = { reference: property?.reference ?? `LOCAL-${crypto.randomUUID()}`, slug: property?.slug ?? "cadastrado", title: v.title.trim(), subtitle: v.subtitle.trim() || "Um lugar para viver novas histórias.", purpose: v.purpose as Property["purpose"], type: v.type as Property["type"], city: v.city.trim(), neighborhood: v.neighborhood.trim(), development: v.development.trim(), cep: v.cep, street: v.street.trim(), addressNumber: v.addressNumber.trim(), state: v.state.trim(), price: Number(v.price), ...(v.purpose === "ambos" ? { rentPrice: Number(v.rentPrice) } : {}), condominium: numeric("condominium"), iptu: numeric("iptu"), builtArea: isLand ? null : numeric("builtArea"), landArea: numeric("landArea"), bedrooms: noRooms ? 0 : Number(v.bedrooms), bathrooms: noRooms ? 0 : Number(v.bathrooms), suites: noRooms ? 0 : Number(v.suites), parking: Number(v.parking), description: [v.description.trim()], features: tags, amenities: [], colors: v.color ? [v.color === "other" ? capitalize(v.otherColor) : v.color] : [], images: draft.photos, sourceUrl: "", consultedAt: property?.consultedAt ?? new Date().toISOString() };
    try { save(item); finished.current = true; setPublished(item); await writeDraft(key, null); } catch (reason) { if (finished.current) setCache("Imóvel salvo; não foi possível limpar o rascunho."); else setError((reason as Error).message); }
  }
  const field = (key: string, label: string, required = false, type = "text") => <label key={key}>{label}<input name={key} list={key === "development" ? "team-developments" : undefined} value={v[key]} onChange={(event) => patch({ [key]: key === "cep" ? event.target.value.replace(/\D/g, "").slice(0, 8).replace(/(\d{5})(\d)/, "$1-$2") : event.target.value })} required={required} type={type} maxLength={key === "cep" ? 9 : key === "otherColor" ? 50 : 120} inputMode={key === "cep" ? "numeric" : undefined} /></label>;
  const selectFields = <><label>Finalidade<select aria-label="Finalidade" value={v.purpose} onChange={(event) => patch({ purpose: event.target.value, price: "", rentPrice: "" })}><option value="">Selecione a finalidade</option><option value="venda">Venda</option><option value="locacao">Locação</option><option value="ambos">Venda ou locação</option></select></label><label>Tipo<select aria-label="Tipo" value={v.type} onChange={(event) => patch({ type: event.target.value })}>{propertyTypes.map((type) => <option key={type}>{type}</option>)}</select></label></>;
  const addressFields = <>{field("cep", "CEP")}{field("addressNumber", "Número / S/N")}{field("city", "Cidade", true)}{field("neighborhood", "Bairro", true)}{field("street", "Rua")}{field("state", "UF")}{field("development", "Condomínio / empreendimento")}<p className="editor-note full-field" role="status">{cepStatus || "Informe o CEP para preencher o endereço. Condomínio é opcional."}</p></>;
  const prices = <><MaskedField label={v.purpose === "locacao" ? "Aluguel mensal" : v.purpose ? "Preço de venda" : "Valor do imóvel"} unit="R$" value={v.price} onChange={(value) => patch({ price: value })} required />{v.purpose === "ambos" && <MaskedField label="Aluguel mensal" unit="R$" value={v.rentPrice} onChange={(value) => patch({ rentPrice: value })} required />}<MaskedField label={isLand ? "Área do terreno" : "Área construída"} unit="m²" value={isLand ? v.landArea : v.builtArea} onChange={(value) => patch({ [isLand ? "landArea" : "builtArea"]: value })} required /></>;
  if (!ready) return <main id="conteudo" className="container editor-page"><p>Recuperando seu rascunho…</p></main>;
  if (published) return <main id="conteudo" className="container editor-page editor-success"><Check size={40} strokeWidth={1} /><span className="eyebrow">TUDO CERTO</span><h1>{property ? "Detalhes atualizados." : "Seu imóvel entrou na seleção."}</h1><p>{published.title} · {money(published.price)}</p><Link className="button button-gold" href={propertyHref(published)}>Ver anúncio <ArrowUpRight size={16} /></Link><Link href="/equipe/" className="back-link">Voltar à equipe</Link><p className="editor-note">Cadastro salvo neste navegador.</p></main>;
  return <main id="conteudo" className="container editor-page"><Link href="/equipe/" className="back-link"><ArrowLeft size={15} /> Voltar à equipe</Link><div className="editor-heading"><div><span className="eyebrow">ÁREA DA EQUIPE</span><h1>{property ? "Cada detalhe, no seu lugar." : "Um novo endereço."}</h1><p>Apresente o imóvel com clareza. Nós ajudamos com o texto.</p></div><button className="button editor-ai-button" onClick={() => setDraft((current) => ({ ...current, aiOpen: true }))}><Sparkles size={17} /> Ajuda com IA</button></div><div className="editor-cache"><span role="status">{cache}</span><button onClick={() => setDiscard(true)}>Descartar rascunho</button></div>
    <datalist id="team-developments">{developments.map((name) => <option key={name} value={name} />)}</datalist><form className="property-form editor-form" noValidate onSubmit={submit}><fieldset id="endereco"><legend>Imóvel e endereço</legend><div className="staff-fields">{selectFields}{addressFields}</div></fieldset><fieldset id="caracteristicas"><legend>Valores e características</legend><div className="staff-fields">{prices}{!isLand && <MaskedField label="Área do terreno" unit="m²" value={v.landArea} onChange={(value) => patch({ landArea: value })} />}<MaskedField label="Condomínio mensal" unit="R$" value={v.condominium} onChange={(value) => patch({ condominium: value })} /><MaskedField label="IPTU mensal" unit="R$" value={v.iptu} onChange={(value) => patch({ iptu: value })} />{(!noRooms ? [["bedrooms", "Dormitórios"], ["bathrooms", "Banheiros"], ["suites", "Suítes"], ["parking", "Vagas"]] : [["parking", "Vagas"]]).map(([key, label]) => <label key={key}>{label}<input type="number" inputMode="numeric" min="0" max="30" step="1" value={v[key]} required onChange={(event) => patch({ [key]: event.target.value })} /></label>)}<label>Cor / tom<select aria-label="Cor / tom" value={v.color} onChange={(event) => patch({ color: event.target.value })}><option value="">Não informado</option>{colors.map((color) => <option value={color} key={color}>{capitalize(color)}</option>)}<option value="other">Outros</option></select></label>{v.color === "other" && field("otherColor", "Outra cor", true)}<div className="full-field feature-editor"><label>Diferenciais<input value={draft.tagInput} maxLength={120} placeholder="Digite e confirme com Enter ou vírgula" onChange={(event) => { const value = event.target.value; if (value.includes(",")) commitTags(value); else setDraft((current) => ({ ...current, tagInput: value })); }} onKeyDown={(event) => { if (event.key === "Enter" && !event.nativeEvent.isComposing) { event.preventDefault(); commitTags(); } }} onBlur={() => { if (draft.tagInput.trim()) commitTags(); }} /></label><div className="feature-tags">{draft.tags.map((tag) => <span key={tag}>{tag}<button type="button" aria-label={`Remover ${tag}`} onClick={() => setDraft((current) => ({ ...current, tags: current.tags.filter((item) => item !== tag), aiConfirmed: false, aiProposal: null }))}><X size={13} /></button></span>)}</div><small>{tagStatus || "Cada diferencial vira uma tag. A escrita é padronizada automaticamente."}</small></div></div></fieldset>
    <fieldset id="apresentacao"><legend>Apresentação</legend><div className="staff-fields"><div className="full-field">{field("title", "Título", true)}</div><div className="full-field">{field("subtitle", "Frase de destaque")}</div><label className="full-field">Descrição<textarea aria-label="Descrição" value={v.description} rows={6} maxLength={2000} required onChange={(event) => patch({ description: event.target.value })} /></label><button type="button" className="profile-preview" onClick={() => setDraft((current) => ({ ...current, aiOpen: true }))}><Sparkles size={15} /> Gerar título e descrição com IA</button></div></fieldset>
    <fieldset id="fotografias"><legend>Fotografias do imóvel</legend><label className="editor-upload"><ImagePlus size={28} strokeWidth={1} /><strong>Adicione as fotos deste endereço.</strong><span>Até 6 fotos JPG, PNG ou WebP de 5 MB. A primeira será a capa.</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={(event) => { void upload(event.target.files); event.target.value = ""; }} /></label><div className="editor-photos">{draft.photos.map((photo, index) => <div key={photo.path}><Image src={asset(photo.path)} alt={`Foto ${index + 1}${index === 0 ? ", capa" : ""}`} width={180} height={130} /><span>{index === 0 ? "Capa" : `Foto ${index + 1}`}</span><button type="button" aria-label={`Remover foto ${index + 1}`} onClick={() => setDraft((current) => ({ ...current, photos: current.photos.filter((_, item) => item !== index) }))}><X size={16} /></button>{index > 0 && <button type="button" className="set-cover" onClick={() => setDraft((current) => ({ ...current, photos: [photo, ...current.photos.filter((_, item) => item !== index)] }))}>Usar como capa</button>}</div>)}</div></fieldset>
    {error && <p className="ai-error" role="alert">{error}</p>}<label className="editor-confirm publish-confirm"><input type="checkbox" checked={publishConfirmed} onChange={(event) => setPublishConfirmed(event.target.checked)} /> Conferi os dados, valores e fotografias deste anúncio.</label><div className="editor-publish"><p className="editor-note">Cadastro e fotos ficam neste navegador. A IA recebe apenas os dados necessários ao texto e as tags para revisão; sem fotos, CEP ou número do endereço.</p><button className="button button-gold" disabled={busy || !publishConfirmed} type="submit">{busy ? "Preparando fotos…" : property ? "Salvar alterações" : "Publicar imóvel"}<ArrowUpRight size={17} /></button></div></form>
    {draft.aiOpen && <Modal title="Ajuda com IA" className="editor-ai-modal" onClose={() => { aiController.current?.abort(); setAiBusy(false); setDraft((current) => ({ ...current, aiOpen: false })); }}><span className="eyebrow"><Sparkles size={14} /> ASSISTENTE ALDENN</span><h2>Vamos apresentar este lugar?</h2><div className="editor-chat-message"><p>{missing.length ? `Para criar um texto fiel, ainda preciso de: ${missing.join(", ")}.` : "Já temos o essencial. Confira os dados abaixo; vou preparar um título e uma descrição usando somente essas informações."}</p><small>O condomínio é opcional. O CEP preenche o endereço; número e demais dados precisam da sua confirmação.</small></div><div className="staff-fields">{selectFields}{addressFields}{prices}{!noRooms && <>{field("bedrooms", "Dormitórios", true, "number")}{field("bathrooms", "Banheiros", true, "number")}</>}</div><p className="editor-note">Diferenciais: {draft.tags.join(", ") || "Nenhum informado"}. A OpenAI recebe tipo, região, valores, área, quartos, banheiros e diferenciais. Não inclua informações pessoais.</p><label className="editor-confirm"><input type="checkbox" checked={draft.aiConfirmed} onChange={(event) => setDraft((current) => ({ ...current, aiConfirmed: event.target.checked }))} /> Conferi os dados e quero uma sugestão de título e descrição.</label>{missing.length > 0 && <p className="editor-note">Para liberar a geração, complete: {missing.join(", ")}.</p>}{aiError && <p role="alert" className="ai-error">{aiError}</p>}<button className="button button-gold" disabled={aiBusy || missing.length > 0 || !draft.aiConfirmed} onClick={() => void generate()}>{aiBusy ? "Preparando o texto…" : "Gerar sugestão"}<Sparkles size={16} /></button>{draft.aiProposal && <div className="editor-proposal"><span className="eyebrow">SUGESTÃO PARA REVISAR</span><h3>{draft.aiProposal.title}</h3><p>{draft.aiProposal.description}</p><button className="button button-dark" onClick={() => setDraft((current) => ({ ...current, values: { ...current.values, ...current.aiProposal! }, aiOpen: false }))}>Usar este texto <Check size={16} /></button><small>Você pode editar o texto antes de publicar.</small></div>}</Modal>}
    {discard && <Modal title="Descartar rascunho" onClose={() => setDiscard(false)}><h2>Começar novamente?</h2><p>O rascunho será apagado. Um imóvel já publicado permanece na seleção.</p><button className="button button-dark" onClick={async () => { try { await writeDraft(key, null); setDraft(initialDraft(property)); setDiscard(false); setError(""); } catch (reason) { setError((reason as Error).message); setDiscard(false); } }}>Descartar rascunho</button></Modal>}
  </main>;
}
function MaskedField({ label, unit, value, onChange, required = false }: { label: string; unit: string; value: string; onChange: (value: string) => void; required?: boolean }) {
  const parts = value.split("."); const formatted = parts[0] ? Number(parts[0]).toLocaleString("pt-BR") + (parts.length > 1 ? `,${parts[1]}` : "") : "";
  return <label>{label}<span className={`masked-field${value ? " has-value" : ""}`}>{value && unit === "R$" && <span>R$</span>}<input aria-label={label} inputMode="decimal" required={required} value={formatted} maxLength={22} placeholder={required ? "Informe o valor" : "Não informado"} onChange={(event) => { const raw = event.target.value.replace(/[^\d,]/g, "").split(","); onChange(raw[0].replace(/^0+(?=\d)/, "").slice(0, 10) + (raw.length > 1 ? "." + raw[1].slice(0, 2) : "")); }} />{value && unit === "m²" && <span>m²</span>}</span></label>;
}
