import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Bath, BedDouble, CarFront, Check, MapPin, Ruler } from "lucide-react";
import { Gallery } from "@/components/gallery";
import { Contact } from "@/components/contact";
import { Financing } from "@/components/financing";
import { PropertyCard } from "@/components/property-card";
import { PropertyVideo } from "@/components/property-video";

import { purposeLabel, landTypes, commercialTypes, type Property } from "@/lib/property";
import { money, number, preciseMoney } from "@/lib/format";

export function PropertyDetail({ property, allProperties = [] }: { property: Property; allProperties?: Property[] }) {
  const isLand = landTypes.includes(property.type), hasRooms = !isLand && !commercialTypes.includes(property.type);
  const rentalTotal = (property.rentPrice ?? property.price) + (property.condominium ?? 0) + (property.iptu ?? 0);
  const similar = allProperties.filter((item) => item.purpose === property.purpose && item.reference !== property.reference).slice(0, 3);
  return <main id="conteudo"><div className="container detail-top"><Link href={`/?purpose=${property.purpose === "ambos" ? "venda" : property.purpose}#imoveis`} className="back-link"><ArrowLeft size={15} /> Voltar aos imóveis</Link><span className="detail-reference">REF. {property.reference}</span></div>
    <div className="container"><Gallery images={property.images} title={property.title} /></div>
    <div className="container detail-layout"><div className="detail-content"><div className="detail-title"><span className="eyebrow">{purposeLabel(property.purpose).toUpperCase()} · {property.type.toUpperCase()}</span><h1>{property.title}</h1><p className="detail-location"><MapPin size={16} />{property.neighborhood} · {property.city}</p></div>
      <div className="detail-facts"><div><Ruler size={23} strokeWidth={1.3} /><strong>{(isLand ? property.landArea : property.builtArea) === null ? "Não informada" : `${number((isLand ? property.landArea : property.builtArea)!)} m²`}</strong><span>{isLand ? "Área do terreno" : "Área construída"}</span></div>{hasRooms && <div><BedDouble size={24} strokeWidth={1.3} /><strong>{property.bedrooms} dormitórios</strong><span>{property.suites} {property.suites === 1 ? "suíte" : "suítes"}</span></div>}<div><CarFront size={25} strokeWidth={1.3} /><strong>{property.parking} vagas</strong><span>Garagem</span></div>{hasRooms && <div><Bath size={24} strokeWidth={1.3} /><strong>{property.bathrooms ?? "Não informado"}</strong><span>Total de banheiros</span></div>}</div>
      <section className="detail-section"><span className="eyebrow">UM OLHAR MAIS DE PERTO</span><h2>{property.subtitle}</h2>{property.description.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<dl className="area-details"><div><dt>Área construída</dt><dd>{property.builtArea === null ? "Não informado" : `${number(property.builtArea)} m²`}</dd></div><div><dt>Área do terreno</dt><dd>{property.landArea === null ? "Não informado" : `${number(property.landArea)} m²`}</dd></div></dl></section>
      <section className="detail-section"><h2>O que faz parte deste lugar.</h2><ul className="feature-list">{property.features.map((feature) => <li key={feature}><Check size={16} />{feature}</li>)}</ul></section>
      {property.amenities.length > 0 && <section className="detail-section"><h2>No condomínio.</h2><ul className="feature-list">{property.amenities.map((feature) => <li key={feature}><Check size={16} />{feature}</li>)}</ul></section>}
      <PropertyVideo video={property.video3d} cover={property.images[0]} title={property.title} />
      {property.purpose !== "locacao" && <Financing price={property.price} />}
      {!property.reference.startsWith("LOCAL-") && <div className="source-note"><span className="eyebrow">SOBRE ESTE EXEMPLO</span><p>Modelo demonstrativo com imagens ilustrativas do Unsplash. As fotos retratam ambientes de diferentes projetos e não representam o imóvel descrito. Características e valores foram baseados em anúncios consultados em {new Date(property.consultedAt).toLocaleDateString("pt-BR", { timeZone: "America/Sao_Paulo" })}. A Aldenn não comercializa estes imóveis.</p></div>}
    </div><aside className="detail-aside"><div className="price-panel"><span className="eyebrow">{property.purpose !== "locacao" ? "VALOR DE VENDA" : "ALUGUEL MENSAL"}</span><strong className="detail-price">{money(property.price)}{property.purpose === "locacao" && <small>/mês</small>}</strong><dl className="cost-list">{property.purpose === "ambos" && <div><dt>Aluguel mensal</dt><dd>{preciseMoney(property.rentPrice ?? 0)}</dd></div>}<div><dt>Condomínio / mês</dt><dd>{property.condominium === null ? "Não informado" : preciseMoney(property.condominium)}</dd></div><div><dt>IPTU / mês</dt><dd>{property.iptu === null ? "Não informado" : preciseMoney(property.iptu)}</dd></div>{property.purpose !== "venda" && <div className="rental-total"><dt>Total mensal informado</dt><dd>{preciseMoney(rentalTotal)}</dd></div>}</dl>{property.purpose !== "locacao" && <a className="finance-link" href="#financiamento">Simular financiamento <ArrowUpRight size={16} /></a>}<Contact property={property.title} reference={property.reference} /><span className="panel-ref">{property.reference.startsWith("LOCAL-") ? "Imóvel cadastrado" : `Imóvel de referência · ${property.reference}`}</span></div></aside></div>
    {similar.length > 0 && <section className="container similar-section"><div className="section-heading"><div><span className="eyebrow">CONTINUE EXPLORANDO</span><h2>Outros lugares,<br /><em>novas possibilidades.</em></h2></div><Link className="text-link" href={`/?purpose=${property.purpose === "ambos" ? "venda" : property.purpose}#imoveis`}>Ver a seleção <ArrowUpRight size={17} /></Link></div><div className="property-grid">{similar.map((item) => <PropertyCard key={item.reference} property={item} />)}</div></section>}
  </main>;
}
